language: ruby
sudo: required
services:
  - docker
rvm:
  - 2.3.1
before_script:
  - psql -c "CREATE USER skateparks WITH PASSWORD 'skateparks';" -U postgres
  - rake db:migrate
  - rake test
script:
  - ./build.sh && ./push.sh
