language: ruby
sudo: required
env:
  global:
    - RAILS_ENV = test
branches:
  only:
    - master
services:
- docker
rvm:
- 2.3.1
before_script:
- docker-compose -f travis_compose.yml up --build -d
script:
- docker ps -a
- docker-compose run web rake db:create
- docker-compose run web bundle exec rake db:test:prepare
- docker-compose run web bundle exec rake test
- chmod +x *.sh
- ./build.sh && ./push.sh
env:
  global:
  - secure: Rzvjd4ejus6N5oNxCmxTxSZpUHDfpaNAxdeXbqrrsRbgauZBMoTtaI2Bw2F8a/uFHsMx3j6dE9b8I1zbBzS6S0s1TXhv+m7CGiu6nZfZOeEMlcDdkuyMfPcV1SKXDkRfMXu3GPoUJcfdmoG/5QqTyZx5MTDJLN/zorhXZ8P24pxDR529bVfmHZ+MwzJY2ASchFtGeuSjQRrvFUitbYUvYMQS0TszXuMqxXDgkJgpj570jSDGMpk8zi0t8r6U5ylrAq8k+MFrRFS6z31ZEZx8ryxWhRRDZ7FBGdCXx3t6n5mfvuv/h5iKCFh+P1sNTH6CLkW9l4poyXorFBYvMGOtBEH8++Xo6bk4FGlGEDRuckwkQl2v/qI+/e5D7vW0ISz88WPdO63jXQphzw69BSz5wTSPBYSoBrCAQIoVywcWPBEIzwg/HQRUH45aU6Pjf48q6FhgpgDIi6U0PJg8/JJHvNayjUmFN+OP1Iy/j+kuvXgWdKF2obYZ4e7yA8ca0BAaz6nBbSzUelovN/5kuom8+fAOtrWmPauIoEq19aAQbePUqXdghHGsSXulhbTvojIvU581aL+NiGA99XPmHYn0ktfD7qTHykrF59lTWV2EwfleoMVjD6USrRv/LTqJjqqLSyHnvavt1CoblpzJYMbM3wYonJt57WkJT94igaZfrLI=
  - secure: f+8vXOpE1fN1m9akVDJzzt8baYOQ5GlYCWKlluUQg1YAyCZnaGBKFhOATqk3+HI4rFIW6DMVgaACONsSqkc3U+h/9Gqk6j2hcsErLcvTelqQFRpyx1DG/TJaheRlM8ObKti4Gqud9QkgVSPQRPTUIdEnyCOYvFLiqMlJIHtuyJIkkOiIuT9FWe0lk+sOL1ppOUxfcEc9Mnb+dMOgUiNspf3VK4Kp0e1NoAlVDXnj/NuOdK3K2Lo0uU3A4ybBMgAtQwyPx9BQpR2dCZB2j4QiQQiSciVRn3KM5LsUDzYq4YI4ve/B9CwPCjAwnXMcfXnw1gBTt/xj7oZLXqVQmHT0zMe0GJuavx/mSE8ysk4WU+k57icBIPmA1X0+QmbqoglOLe4lIEbjQoG4NSQuR4Q4G+Qfp0o/KvM1JyWF2SKKgGqKfKRlFIg8Fhj/nco8GTtsW0g8lPt/x+GRj0J+rcsmPkqEGBAYKkZ3fmDXrUYS18cFhRzVehSYHbflJI7e4Zx1mcoqJNL1YPjyiGANUU5aumrIgDSMddhV9GsECmSjSXITXdFs5mLWaCRF+tmOixduL31xplBk6IAMtNH3dILeG3lVgTrrRhL+mlFEf5sMDnwHNbAgA4rh2VBfC9b5OH2nCyvs6Xbvoq8W9OEynt1FXmnRTqvfmF3BAbMdN0e5Ack=
